___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
import numpy as np
import pandas as pd



In [ ]:
from google.colab import drive
drive.mount('/content/drive')

### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [ ]:
my_list=array=np.arange(5,30,5)
my_list

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros. 

In [ ]:
# YOUR CODE IS HERE
my_zeros=np.zeros((5,5))
my_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [ ]:
# YOUR CODE IS HERE
my_ones=np.ones(((4,4)), dtype=int)
my_ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [ ]:
# YOUR CODE IS HERE
my_ones[my_ones==1]=7
my_ones

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 6. Create the previous array above by full() method.

In [ ]:
# YOUR CODE IS HERE
my_sevens_2= np.full(([4, 4]), 7, dtype=int)
my_sevens_2
#or 
my_sevens2=np.full_like(my_ones,7)
my_sevens2

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive). 

In [ ]:
# YOUR CODE IS HERE
array=np.arange(2,17,2)
array

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [ ]:
# YOUR CODE IS HERE
arr1=np.random.randint(0,25,25).reshape(5,5)
print(arr1,'\n')
print(np.min(arr1))
print(np.max(arr1))

[[ 5 22 14  0  6]
 [19 17  3 10 15]
 [17 16  1 20 24]
 [ 0 11  7 23  6]
 [15 21  0 23  3]] 

0
24


### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [ ]:
# YOUR CODE IS HERE
my_linspace=np.linspace(0,24,25).reshape(5,5)
my_linspace


array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

### 10. Create randomly 5 numbers with numpy.

In [ ]:
# YOUR CODE IS HERE
my_random=np.random.rand(5)
my_random

array([0.72079277, 0.14656964, 0.95732063, 0.88208683, 0.75052033])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [ ]:
# YOUR CODE IS HERE
my_random=np.random.rand(25).reshape(5,5)
my_random

array([[0.68978669, 0.14593109, 0.12063569, 0.35915051, 0.49201118],
       [0.10009462, 0.46861433, 0.12402075, 0.63499981, 0.18041527],
       [0.42344355, 0.00471816, 0.0850422 , 0.6850462 , 0.04275076],
       [0.18755508, 0.49879254, 0.18669473, 0.65301664, 0.39765115],
       [0.10354   , 0.163252  , 0.95580412, 0.98932535, 0.84474927]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [ ]:
# YOUR CODE IS HERE
a = np.random.randint(20,50, size = (3, 4))
a

array([[41, 23, 20, 27],
       [39, 41, 35, 26],
       [31, 22, 31, 48]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [ ]:
# YOUR CODE IS HERE ???
ranarr=np.random.randint(48, size=(6,8))
ranarr

array([[46, 15, 13, 41,  7,  7,  0,  2],
       [24, 22, 32, 29, 22, 41, 41, 22],
       [15,  1, 34, 38, 17, 11,  5, 15],
       [44, 18, 13, 40,  5, 27,  2,  0],
       [10,  6, 34,  6, 24,  9, 21, 31],
       [33,  3, 37, 32, 28, 13, 39, 34]])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr2=np.arange(1,49,1).reshape(6,8)
ranarr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48]])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
rannarr = np.random.randint(1, 49, (6,8))
rannarr

array([[31,  2, 35, 35, 47,  8,  5, 32],
       [13, 24, 10, 13, 15, 22, 15, 23],
       [15, 20, 42, 38, 26, 46, 13, 11],
       [ 4, 42, 26, 35, 37, 47,  1, 23],
       [29, 22,  9, 34, 26, 12, 21, 34],
       [ 9,  1, 40, 42, 12, 32, 21, 32]])

In [ ]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
????


## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [ ]:
# YOUR CODE IS HERE 
mat=np.arange(1,17,1).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [ ]:
# YOUR CODE IS HERE 
mat[1:3,1:3] # I did not understand it why we put 3 instead of 2 because these numbers are between (1,2)X (1,2) matrices??

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [ ]:
# YOUR CODE IS HERE 
mat[:, [0]]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [ ]:
# YOUR CODE IS HERE 
mat[[1],::2]

array([[5, 7]])

### 17.Assign 77 to every cell in 3rd column.

In [ ]:
# YOUR CODE IS HERE 

mat[0:4,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [ ]:
# YOUR CODE IS HERE 
mat[[1,0],[0,2]]

array([ 5, 77])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [ ]:
# YOUR CODE IS HERE 
mat[[1,3],::2]


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 
mat
# YOUR CODE IS HERE 
mat[(mat<10) & (mat>12)]
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [ ]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat" 

# YOUR CODE IS HERE 
x=mat[mat<10]
x

array([1, 2, 4, 5, 6, 8, 9])

In [ ]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat" 

# YOUR CODE IS HERE 
y=mat[mat>12]
y

array([77, 77, 77, 13, 14, 77, 16])

In [ ]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat" 

z = np.add(x, y)
z

array([78, 79, 81, 18, 20, 85, 25])

### 21. Get the standard deviation (std) of the result above.

In [ ]:
# YOUR CODE IS HERE 
np.std(z)


29.700546274093877

### 22. Get the sum of the 2nd column in the original "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
print(mat,'\n')

[[ 1  2 77  4]
 [ 5  6 77  8]
 [ 9 10 77 12]
 [13 14 77 16]] 



In [ ]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat" 
print(mat,'\n')
# YOUR CODE IS HERE 
mat_copy=mat.copy()
mat_copy[0:4,2]=3,7,11,15 # rows 0 to 4 and fill column  2 with original values
mat_copy


[[ 1  2 77  4]
 [ 5  6 77  8]
 [ 9 10 77 12]
 [13 14 77 16]] 



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
# YOUR CODE IS HERE 
print(mat_copy,'\n')
#np.sum(mat_copy[:,1]) or 
y=mat_copy[:,1]
print(y,'\n')
np.sum(y)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 

[ 2  6 10 14] 



32

### 23. Get the median, mean and std of 3rd column in "mat".

In [ ]:
# LET US REMEMBER OUR ARRAY OF "mat" 

# YOUR CODE IS HERE 
x=mat_copy[:,2]
print(x)
print(np.median(x))
print(np.mean(x))
print(np.std(x))
print()


[ 3  7 11 15]
9.0
9.0
4.47213595499958



In [ ]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE 

# YOUR CODE IS HERE 
print(mat_copy,'\n')
j=mat_copy[::,2]
j 


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]] 



array([ 3,  7, 11, 15])

In [ ]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW? 

# YOUR CODE IS HERE 

h=mat_copy[2,::]
h

array([ 9, 10, 11, 12])

In [ ]:
# LET US GET MEDIAN VALUE 

# YOUR CODE IS HERE 

print(np.median(j))
print(np.median(h))

9.0
10.5


In [ ]:
# LET US GET MEAN VALUE 

# YOUR CODE IS HERE 

print(np.mean(j))
print(np.mean(h))

9.0
10.5


In [ ]:
# LET US GET STANDART DEVIATION (std) VALUE 

# YOUR CODE IS HERE 
print(np.std(j))
print(np.std(h))


4.47213595499958
1.118033988749895


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [2]:
import pandas as pd
import numpy as np

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

In [3]:
# LET US READ Salaries.csv 

# YOUR CODE IS HERE 
from google.colab import drive
drive.mount('/content/drive')
from google.colab import files
df =pd.read_csv("/content/drive/MyDrive/Salaries.csv")



Mounted at /content/drive


In [ ]:
# LET US LOOK AT THE FIRST 5 ROWS 

# YOUR CODE IS HERE 
df.head()


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [ ]:
# LET US GET A SAMPLE 

# YOUR CODE IS HERE 

df.sample(1)

Id     EmployeeName                  JobTitle   BasePay  \
121265  121266  Niger M Edwards  Senior Personnel Analyst  99145.11   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
121265          0.0       0.0  36527.23  99145.11         135672.34  2014   

        Notes         Agency  Status  
121265    NaN  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [ ]:
# YOUR CODE IS HERE 
list(df.columns.values)##???
for i in df.columns:# attention . colon sign
           print(i)
print()
df.info()

Id
EmployeeName
JobTitle
BasePay
OvertimePay
OtherPay
Benefits
TotalPay
TotalPayBenefits
Year
Notes
Agency
Status

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 

In [ ]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS  

# YOUR CODE IS HERE 
df.describe()


Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [ ]:
# YOUR CODE IS HERE 
df1=pd.DataFrame(df)## 
pd.value_counts(df1['Year'])
df1.groupby('Year').count()
df1['Year'].value_counts()
df['Year'].size
df1['Year'].value_counts() # this is the exact formula

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [ ]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 

df['Year'].nunique() # !!!

4

In [ ]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE 
df['Year'].unique()

array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [ ]:
from numpy.lib.shape_base import column_stack
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE 
print("TotalPay max      :",max(df.TotalPay))
print("TotalPay mean     :",np.mean(df.TotalPay))
print("TotalPay min      :",df["TotalPay"].min())
print("TotalPay  max     :",df["TotalPay"].max())
print("TotalPay mean     :",df["TotalPay"].mean())


TotalPay max      : 567595.43
TotalPay mean     : 74768.32197169267
TotalPay min      : -618.13
TotalPay  max     : 567595.43
TotalPay mean     : 74768.32197169267


In [ ]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE 

print("TotalPay average is  :",df["TotalPay"].mean())


TotalPay average is  : 74768.32197169267


### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
# YOUR CODE IS HERE 
my_mean=df["TotalPay"].mean()
TotalPay_High= [(df['TotalPay'] > my_mean).count()]
TotalPay_High
TotalPay_High= df[df['TotalPay'] > df["TotalPay"].mean()].count()
TotalPay_High
TotalPay_Higher=df.loc[(df['TotalPay'] >= my_mean)] # this is the magic formula
TotalPay_Higher

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE 

nr=df.loc[(df['TotalPay'] >= my_mean)].count()
nr

Id                  69489
EmployeeName        69489
JobTitle            69489
BasePay             69480
OvertimePay         69489
OtherPay            69489
Benefits            53642
TotalPay            69489
TotalPayBenefits    69489
Year                69489
Notes                   0
Agency              69489
Status                  0
dtype: int64

### How much does ALBERT PARDINI make money (including benefits)?

In [ ]:
# YOUR CODE IS HERE 
ap_salary= df[df['EmployeeName'] == 'ALBERT PARDINI']['TotalPayBenefits']
ap_salary

2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [ ]:
# YOUR CODE IS HERE 
lowest_paid=df.loc[df['TotalPay'].idxmin()]
lowest_paid


Id                                      148654
EmployeeName                         Joe Lopez
JobTitle            Counselor, Log Cabin Ranch
BasePay                                    0.0
OvertimePay                                0.0
OtherPay                               -618.13
Benefits                                   0.0
TotalPay                               -618.13
TotalPayBenefits                       -618.13
Year                                      2014
Notes                                      NaN
Agency                           San Francisco
Status                                     NaN
Name: 148653, dtype: object

### What are the unique Jobs in dataset?

In [ ]:
# YOUR CODE IS HERE 

df['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [ ]:
# YOUR CODE IS HERE 
grouped = df.groupby('JobTitle').count()
Min3 = grouped.sort_values(by='Id',  ascending=True)[:3]
Min3['Id']


JobTitle
ZOO CURATOR                               1
DIRECTOR, INFORMATION TECHNOLOGY GROUP    1
DIRECTOR, HUMAN RESOURCES                 1
Name: Id, dtype: int64

### How many people earned more than avg in 2012?

In [ ]:
# YOUR CODE IS HERE 
cond = df[df["TotalPayBenefits"] > df["TotalPayBenefits"].mean()][df["Year"] == 2012].count()
cond.isin(df)
cond
#year_2012.loc[(year_2012['TotalPay'] >= my_mean)].count()
#year_2012

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


Id                  20366
EmployeeName        20366
JobTitle            20366
BasePay             20366
OvertimePay         20366
OtherPay            20366
Benefits            20366
TotalPay            20366
TotalPayBenefits    20366
Year                20366
Notes                   0
Agency              20366
Status                  0
dtype: int64

### How many people have a title of Manager in their jobs?

In [ ]:
# USE APPLY FUNCTION
# YOUR CODE IS HERE 

????

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [ ]:
# YOUR CODE IS HERE 
df.head()
sal_new = df.iloc[:, [0,1,2,7,8]]
sal_new


Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [ ]:
# YOUR CODE IS HERE 
df.head()
sal_new2= pd.DataFrame(sal_new)
sal_new2=sal_new2.loc[:, 'EmployeeName':'TotalPayBenefits']
sal_new2



EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [36]:
# YOUR CODE IS HERE 

df.head()
my_min=[df['TotalPay'].idxmin()]
my_minx=((df['TotalPay'] > my_min())
my_mean=df["TotalPay"].mean()
df.EmployeeName.groupby((df['TotalPay'] < my_mean)).count()
grouped=((df['TotalPay'] < my_mean) & (df['TotalPay'] > my_min))

SyntaxError: ignored

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________